name: Check Python Dict

on:
  push:
  workflow_dispatch:

jobs:
  check-dict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Debug Repository
      run: ls -R

    - name: Check if dict has values
      run: |
        python -c "
        try:
            import test1 as data
            if not data.my_dict:
                print('❌ Dictionary is empty. Failing workflow.')
                exit(1)
            else:
                print('✅ Dictionary has values. Workflow continues.')
        except ModuleNotFoundError:
            print('❌ Module \"data\" not found. Ensure test1.py exists in the repository.')
            exit(1)"