name: Check Python Dict

on:
  push:
    branches:
      - dev  # Automatically trigger on push to dev branch
  workflow_dispatch:
    inputs:
      dict_key:
        description: "Key to check in the dictionary"
        required: true
        default: "key1"
      dict_value:
        description: "Value to set for the key"
        required: false
        default: "100"

jobs:
  check-dict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Debug Repository
      run: ls -R

    - name: Check and Set Dict Values
      run: |
        python -c "
        try:
            import test1 as data
            key = '${{ github.event.inputs.dict_key }}'
            value = int('${{ github.event.inputs.dict_value }}')

            if key in data.my_dict:
                print(f'✅ Key \"{key}\" exists with value: {data.my_dict[key]}')
            else:
                print(f'❌ Key \"{key}\" does not exist. Adding it with value: {value}')
                data.my_dict[key] = value

            print(f'Updated Dictionary: {data.my_dict}')
        except ModuleNotFoundError:
            print('❌ Module \"data\" not found. Ensure test1.py exists in the repository.')
            exit(1)"